favicon: /favicon.ico


# Nav Menus
menu:
    Index: /
    Archives: /archives

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github/fredliu168']
    - ['/images/rss.svg', '/atom.xml']

# Friend Links
friend_links:
    - ['restran', '淡水', 'https://www.restran.net']
    - ['iReading', '英语学习,经济学人在线阅读', 'https://qzcool.xyz']

# About
about_info:
    name: "Fishman"
    bio: "且行且珍惜"
    avatar: "/images/avatar.png"

# Comment
# e.g disqus: seansun
disqus: fishman-1
duoshuo: 

auto_excerpt:
  enable: true
  length: 150

# Analytics
google_analytics: fishman
tencent_analytics: 
 
# Copyright Infomation
startyear: 2017
