favicon: /favicon.ico

# Nav Menus
menu:
  Index: /
  Archives: /archives

# Nav Shortcut Icons
nav_icons:
  - ['/images/github.svg', 'https://github.com/fredliu168']
  - ['/images/rss.svg', '/atom.xml']

# Friend Links
# friend_links:
#  - ['xxx', 'xxx', 'https://www.xxx.net']

# About
about_info:
  name: 'fred'
  bio: 'follow your heart'
  avatar: '/images/avatar.png'

# Comment
# e.g disqus: seansun
disqus: fishman-1
duoshuo:

auto_excerpt:
  enable: false
  length: 150

# Analytics
google_analytics: fishman
tencent_analytics:

# Copyright Infomation
startyear: 2017
